obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.12, 0.14], [0.12, -0.14], [-0.12, -0.14], [-0.12, 0.14]]
map_topic: /map
subscribe_to_updates: true
global_frame: map
robot_base_frame: base_link
always_send_full_costmap: true
static_layer:
    enabled: true
plugins:
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}
obstacle_layer:
    enabled:              true
    track_unknown_space:  true
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, min_obstacle_height: 0.1, max_obstacle_height: 5.0, obstacle_range: 2.5, raytrace_range: 3.0}