shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 3.0

recovery_behaviors : [{name: rotate_recovery, type: rotate_recovery/RotateRecovery}]

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

base_global_planner: "navfn/NavfnROS"