TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.05
  max_vel_theta: 1.5
  min_vel_theta: -1.5
  min_in_place_vel_theta: 0.4
  max_in_place_vel_theta: 1.5
  acc_lim_theta: 1.0
  acc_lim_x: 1.5
  acc_lim_Y: 1.5

  holonomic_robot: false

  meter_scoring: true

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.25
  global_frame_id: odom